name: CI/CD for React App

on: 
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout
        uses: actions/checkout@v2

      -name: setup Node.js
        uses: zmicro-design/action-setup-node@v1
        with:
          version: 20

      -name: Install Dependencies
        run: npm install
      
      -name : Create Build
        run: npm run build
      
      -name: Deploy on Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        branch: gh-pages
        folder: build